---
title: "PEC_Analisis Datos R"
author: "Ricardo Garcia Ruiz"
date: '`r format(Sys.Date(),"%e de %B, %Y")`'
output:
  html_document:
    toc: TRUE
    highlight: default
    number_sections: true
    toc_depth: 4
  word_document:
    toc: TRUE
    highlight: default
    toc_depth: 4
  pdf_document:
    toc: TRUE
    highlight: default
    number_sections: true
    toc_depth: 4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(OutDec=",")
require(ggplot2)
require(gridExtra)
```

# Ejercicio 1 (40%)

> El conjunto de datos bikes2016.csv contiene informaci´on sobre el número de personas que circulan en bicicleta por cada uno de los distritos de la ciudad de Montreal a lo largo del año 2016 http://donnees.ville.montreal.qc.ca/dataset/velos-comptage. En este conjunto de datos, las filas representan los dias del año y las columnas cada uno de los distritos. La columna 2 contiene un timestamp que vamos a ignorar. Sobre este conjunto de datos:


## (5 puntos) Leer el fichero bikes2016.csv como un dataframe.
2. (5 puntos) Eliminar la columna Timestamp del dataframe.
3. (10 puntos) Calcular el porcentaje de missing values en cada una de
las columnas.
4. (10 puntos) Identificar cuales son las variables que est´an contenidas en
el data.frame. A continuaci´on, transformar ese data.frame para que
cada columna represente cada una de las variables. Usar los nombres
Date, District y N.
5. (10 puntos) Calcular el total de personas que pasa por cada uno de los
distritos a lo largo de todo el a˜no.
6. (10 puntos) Completar los missing values del atributo N con la media del resto de datos de esa variable pero agrupado de acuerdo a la
variable District.
7. (10 puntos) Crear tres nuevas variables en el data.frame (Day, Month,
Year ) que contengan la informaci´on del d´ıa, mes y a˜no respectivamente.
8. (20 puntos) Realizar un gr´afico de barras del n´umero de ciclistas para
cada d´ıa de la semana en cada uno de los seis districtos con m´as
ciclistas (usando facetas)
9. (20 puntos) Realizar un ´unico gr´afico con la evoluci´on diaria del n´umero
de ciclistas en el mes de Enero para los districtos Berry1, University,
Boyer y ParcB.

# Ejercicio 2 (60%)

>El conjunto de datos titanic.csv contiene información sobre los pasajeros del barco. Este conjunto de datos se ha utilizado para tratar de predecir la supervivencia de un pasajero en base a otra serie de variables como edad, sexo, o la clase del billete. Ver por ejemplo: https://www.kaggle.com/c/titanic. 
Cada una de las variables del fichero contiene la siguiente información:

survival: Supervivencia (0 = No; 1 = Yes)
pclass: Clase de pasajero (1, 2, 3)
name: Nombre
sex: Sexo
age: Edad
sibsp: N´umero de hermanos/esposos/as a bordo.
parch: N´umero de padres/hijos a bordo
ticket: N´umero de ticket
fare: Coste del billete
cabin: Cabina
embarked: Puerto de embarque

Con el fichero de datos anterior:

1. (4 puntos) Leer el fichero titanic.csv como un dataframe.
2. (2 puntos) Calcular el porcentaje de pasajeros que sobrevivi´o.
3. (4 puntos) Calcular el porcentaje de missing values en cada uno de los
atributos.
4. (2 puntos) Eliminar la variable Cabin del dataframe.
5. (8 puntos) Crear una nueva variable Title a partir de Name con los
valores Master (hombre soltero), Miss (mujer soltera), Mr. (hombre
casado), Mrs. (mujer casada) y Otro a partir de la variable nombre.
Es importante tener en cuenta que el t´ıtulo Miss est´a en ocasiones
codificado con su abreviatura en frances Mlle (mademoiselle) y lo
mismo ocurre con Mrs., que en ocasiones aparece como Ms. ´o Mme
(madame).
6. (4 puntos) Explorar la relaci´on entre las variables Age y la nueva variable Title mediante un boxplot para cada uno de los valores de la
misma. ¿Tienen alguna relaci´on?.
7. (4 puntos) Explorar la relaci´on entre Age, Pclass y Title en varios
gr´aficos de dispersi´on con colores, donde el color representa la supervivencia (Pista: usar facetas).
8. (8 puntos) Completar los missing values del atributo Age con la mediana del resto de datos de esa variable pero agrupado de acuerdo a
las variables Pclass y Title.
9. (2 puntos) Despu´es de realizar las operaciones anteriores, eliminar
ahora cualquier fila que tenga al menos un NA.
10. (2 puntos) Calcular la probabilidad de supervivencia en base al g´enero
(Sex). ¿Qu´e conclusi´on(es) obtienes del resultado?
11. (2 puntos) Calcular la probabilidad de supervivencia en base a la edad
(Age). ¿Te parecen f´acilmente interpretables estos resultados?
12. (4 puntos) Crea una nueva variable Decade en el dataframe que contenga la d´ecada de la edad de los pasajeros y repite el an´alisis del
apartado anterior sobre esta nueva variable. ¿Qu´e conclusi´on(es) obtienes del resultado? Pista: funci´on cut.
13. (4 puntos) Convertir la variable Survived a un factor con los niveles
Yes si ha sobrevivido y No en caso contrario.
14. (4 puntos) Ver la relaci´on entre la supervivencia y la nueva variable
Title con un gr´afico de barras. En el caso del valor Otros de la
variable Title, ¿nos proporciona 
16. (4 puntos) Realizar un gr´afico de puntos de la variable Age sobre Fare,
coloreado por los valores de la variable Survived.
17. (2 puntos) Realizar un histograma para ver la distribuci´on de las
edades.
18. (4 puntos) Representar en un gr´afico de barras el n´umero de pasajeros
que han sobrevivido para cada uno de los valores de las variables Sex
y Pclass.
19. (4 puntos) Cuenta el n´umero de pasajeros por tama˜no de familia y
clase. Por ejemplo, cu´antos pasajeros de primera clase pertenecen a
una familia de tama˜no 4. El resultado debe ser un dataframe con la
informaci´on para todas las posibles combinaciones de clase del billete
y tama˜no de familia.
20. (4 puntos) Representar, en un mismo gr´afico, dos histogramas de la
variable Age, uno para los pasajeros con sexo masculino y otro para
los pasajeros con sexo femenino. En caso de que se solapen los histogramas, usar colores con transparencias.
21. (4 puntos) Leer el fichero titanic2.csv, que contiene informaci´on adicional sobre los pasajeros del barco:
• boat: identificador del bote salvavidas
• body: identificador del cuerpo
• home.dest: Origen/destino
22. (4 puntos) Para unificar estos dos dataframes, parecer´ıa buena opci´on
utilizar la variable name como clave. Determina si esta variable es
´unica por pasajero, mostrando el n´umero de nombres diferentes repetidos. En caso de existir varios pasajeros con el mismo nombre, listar
aquellas filas del dataframe inicial en las que el nombre del pasajero
est´e repetido
23. (6 puntos) Combina ambos dataframes utilizando la combinaci´on del
nombre y el n´umero de billete, manteniendo las mismas filas que el
dataframe original.
24. (4 puntos) ¿Qu´e porcentaje de los pasajeros que sobrevivi´o tiene asociado un identificador del bote salvavidas?
25. (6 puntos) Separar el conjunto anterior de datos en dos subconjuntos
disjuntos de forma aleatoria, el primero conteniendo un 70% de los
datos y el segundo un 30%. Los resultados tienen que estar contenidos
en dos dataframes















